FROM python:3.10-slim

WORKDIR /app

# Copy only requirements.txt first
COPY backend/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Now copy the rest of the backend app
COPY backend/ .

# Create folder for file uploads
RUN mkdir -p /app/zoll_uploads

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]

